### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by akshitbtw** [ullaskunder3/Solutions#1]
Hi,
I'm new to GitHub so idk how to ask a query, that's why I'm writing it here.
First of all thanks for this amazing solution. I managed to add the compile options in tasks.json & found a way to run it through code-runner extension.

My query : Do you know how can we combine the 'WIndows BGI' popup window (that comes at the time of running the program) with the terminal?
Because I've been working on user input programs and I have to write the user input separately in the integrated terminal of VS code.
Like in TurboC, the output of printf commands as well as the graphics commands(like line, rectangle, arc) comes in the same window. But in VS code, I've to use the outtextxy command so that the input strings show in the Windows BGI.

Do let me know if you know how to fix this.

**Comment by ullaskunder3** [comment]
Can you share the code if possible? I would like to see exactly what you
are talking about....

**Comment by ullaskunder3** [comment]
User input!

![Screenshot 2021-04-27 001349](https://user-images.githubusercontent.com/66258652/116134716-d66f2400-a6ed-11eb-8867-11f9a9c3aa20.png)

Is this what you are talking about...

**Comment by akshitbtw** [comment]
![code](https://user-images.githubusercontent.com/83155183/116134873-0a4a4980-a6ee-11eb-9a35-f6e4dae84446.png)

In turboc, the user input as well as the graphics come in the same window.
But in vs code, you have to enter the input in the integrated terminal and the output comes in a separate window.
So I was thinking whether there is a way through which we can combine them in the same window.

**Comment by akshitbtw** [comment]
![turboc Output](https://user-images.githubusercontent.com/83155183/116135307-99eff800-a6ee-11eb-8845-cbb2b85a6136.png)

This is how turboc's output looks like.

**Comment by ullaskunder3** [comment]
sorry to disappoint you but I don't think that is possible because vs code and mingw.graphics.h is totally separate...

**Comment by ullaskunder3** [comment]
> ![code](https://user-images.githubusercontent.com/83155183/116134873-0a4a4980-a6ee-11eb-9a35-f6e4dae84446.png)
> 
> In turboc, the user input as well as the graphics come in the same window.
> But in vs code, you have to enter the input in the integrated terminal and the output comes in a separate window.
> So I was thinking whether there is a way through which we can combine them in the same window.

Good thought though...  you might research on it in future may be you can create an extension that do the trick `good look`

**Comment by akshitbtw** [comment]
No Problem Man! Thanks for your time :D
