### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by trevorboultwood** [ullaskunder3/Solutions#11]
I'm trying to get this library working with vscode following your guide but I get a segmentation fault!

I can successfully build the project with ctl+shift+b and this produces a lovely executable. If I try to run this nothing happens, if i open it within the console no error messages are displayed. The segmentation fault appears on initgraph. This is probably something to do with the library .a file...

Thank you!

**Comment by ullaskunder3** [comment]
may I know what's the third parameter are you passing in `initgraph()` @trevorboultwood 

- can I have a screen shot or code example so I can recreate the issue

**Comment by cow03haha** [comment]
i have same problem, can you take a look?

![image](https://user-images.githubusercontent.com/44705326/222140239-13ecdb6e-62f9-4a19-b8e2-7022a8882e8c.png)

**Comment by trevorboultwood** [comment]
Hi Ullaskunder3, I believe I solved my initial problem, whilst I'm not completely sure I suspect the underlying issue is dependent on the compiler being used. I think I was using a 32 bit compiler for the 64bit compiled library.

**Comment by ullaskunder3** [comment]
Awesome
