### ISSUE TITLE
fatal error: graphics.h

### ISSUE THREAD

**Issue by bixash** [ullaskunder3/Solutions#13]
MinGW complier shows this error.
<img width="725" alt="mingw-error" src="https://github.com/ullaskunder3/Solution-to-graphics.h/assets/83506059/0368fc3c-e20d-4258-83bc-22c33ed7c0fc">
But TDM-GCC works fine.
<img width="737" alt="tdm" src="https://github.com/ullaskunder3/Solution-to-graphics.h/assets/83506059/c6bdb1e1-c2f7-497a-999e-83c0036dc7f5">

**Comment by ullaskunder3** [comment]
If it works well for you in another way, that's great! 
 
 - It has been functioning smoothly for more than 40 people using MinGW (which typically offers the latest official GCC releases and is regularly updated with new features and improvements). 
 
 - If a significant number of users encounter the same issue, we can certainly investigate further. 
 *As the saying goes, "Don't tweak if it works."
 
 - I am thinking about updating with few automation w'll soon update
