### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by 0xSarnavo** [ullaskunder3/Solutions#2]
PS C:\Users\Subhajit\Desktop\project\cpp\collage lab\testFolder> g++ -o testfile example.cpp -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32
example.cpp:2:14: fatal error: graphics.h: No such file or directory
    2 |     #include <graphics.h>
      |              ^~~~~~
compilation terminated.

**Comment by ullaskunder3** [comment]
Its not detecting the header file... did you added those file to include and lib folder of mingw as mentioned in README file:
If you dont have MinGW install it from official and follow the steps & make sure you set bin folder to environment variable...
Copy `graphics.h` and `winbgim.h` files to `MinGW/include` folder. Location Might be ("C:\MinGW\include")
Copy `libbgi.a` to file to `MinGW/lib` folder. Location ("C:\MinGW\lib")

**Comment by ullaskunder3** [comment]
> PS C:\Users\Subhajit\Desktop\project\cpp\collage lab\testFolder> g++ -o testfile example.cpp -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32
> example.cpp:2:14: fatal error: graphics.h: No such file or directory
> 2 | #include <graphics.h>
> | ^~~~~~
> compilation terminated.

try again and this time cross verify everything  [project template](https://github.com/ullaskunder3/graphics.h-project-template) let me know...
