### ISSUE TITLE
Incomplete file

### ISSUE THREAD

**Issue by SpiffGreen** [ullaskunder3/Solutions#3]
graphics.h file doesn't contain complete function definitions for some functions

**Comment by ullaskunder3** [comment]
> graphics.h file doesn't contain complete function definitions for some functions

Can you please provide more information then that
Did you fall into an error ? if yes then please specifies...

**Comment by SpiffGreen** [comment]
Sorry, I've not being able to reply you. I had a compile error as it showed the error below.
C:\Users\Spiff\AppData\Local\Temp\ccsxPxOX.o:example.cpp:(.text+0x5d): undefined reference to `initgraph'
C:\Users\Spiff\AppData\Local\Temp\ccsxPxOX.o:example.cpp:(.text+0x79): undefined reference to `circle'
C:\Users\Spiff\AppData\Local\Temp\ccsxPxOX.o:example.cpp:(.text+0x8a): undefined reference to `closegraph'
collect2.exe: error: ld returned 1 exit status

**Comment by ullaskunder3** [comment]
@SpiffGreen It's ok no problem, can you reproduce the code
If yes, can you please share a sample short code that I can just copy and try to reproduce?
Thanks

**Comment by Suryajung8** [comment]
In file included from example.cpp:1:
C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/lib/gcc/i686-w64-mingw32/8.1.0/include/graphics.h:13:10: fatal error: _defs.h: No such file or directory
 #include <_defs.h>
 I'm getting this error

**Comment by ullaskunder3** [comment]
> mingw-w64

Please use MINGW not MingW64 and please follow the documentation for setup graphics.h in vsCode. Know the difference between MINGW, Mingw-w64 && TDM compiler [learn more](https://github.com/ullaskunder3/cpp-setup-vsCode#setup).

- If you want to use the older graphics.h then go for MingW
- If your working with something like SFML or SDL( Go for TDM GCC ) & OPENCV ( Go for MinGW-w64 )

**Comment by ullaskunder3** [comment]
> In file included from example.cpp:1:
> C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/lib/gcc/i686-w64-mingw32/8.1.0/include/graphics.h:13:10: fatal error: _defs.h: No such file or directory
> #include <_defs.h>
> I'm getting this error

@Suryajung8
Please use MINGW not MingW64 and please follow the documentation for setup graphics.h in vsCode. Know the difference between MINGW, Mingw-w64 && TDM compiler [learn more](https://github.com/ullaskunder3/cpp-setup-vsCode#setup).

If you want to use the older **graphics.h** then go for `MingW`
If your working with something like `SFML or SDL( Go for TDM GCC )` & `OPENCV ( Go for MinGW-w64 )`

**Comment by SpiffGreen** [comment]
> @SpiffGreen It's ok no problem, can you reproduce the code
> If yes, can you please share a sample short code that I can just copy and try to reproduce?
> Thanks

I used the code in example.cpp and also the one in the readme. Both gave same error.
I am currently using MinGW target is mingw32

**Comment by SpiffGreen** [comment]
> @SpiffGreen It's ok no problem, can you reproduce the code
> If yes, can you please share a sample short code that I can just copy and try to reproduce?
> Thanks

I used the code in example.cpp and also the one in the readme. Both gave same error.
I am currently using MinGW target is mingw32

**Comment by ullaskunder3** [comment]
please refer my workspace `.vscode` [ullaskunder3 graphics template](https://github.com/ullaskunder3/graphics.h-project-template)

```cmd
D:.
├───.vscode
└───Home
    ├───build
    └───src
```

**Comment by Suryajung8** [comment]
![image](https://user-images.githubusercontent.com/64884975/129924209-efe02865-fde3-4d01-b9ed-4d11c051c0b5.png)
Now I'm getting this error!

**Comment by ullaskunder3** [comment]
> ![image](https://user-images.githubusercontent.com/64884975/129924209-efe02865-fde3-4d01-b9ed-4d11c051c0b5.png)
> Now I'm getting this error!

please refer my workspace `.vscode` [ullaskunder3 graphics template](https://github.com/ullaskunder3/graphics.h-project-template)

```cmd
D:.
├───.vscode
└───Home
    ├───build
    └───src
```

**Comment by Suryajung8** [comment]
> > ![image](https://user-images.githubusercontent.com/64884975/129924209-efe02865-fde3-4d01-b9ed-4d11c051c0b5.png)
> > Now I'm getting this error!
> 
> please refer my workspace `.vscode` [ullaskunder3 graphics template](https://github.com/ullaskunder3/graphics.h-project-template)
> 
> ```batchfile
> D:.
> ├───.vscode
> └───Home
>     ├───build
>     └───src
> ```

I'm trying to compile Hut.cpp the file of yours

**Comment by ullaskunder3** [comment]
@Suryajung8 @SpiffGreen 
- We need to configure OR specify where the graphics.h file and the include file located thats why we need `c_cpp_properties.json` [c_cpp_properties](https://github.com/ullaskunder3/graphics.h-project-template/blob/main/.vscode/c_cpp_properties.json), `task.json` [task.json](https://github.com/ullaskunder3/graphics.h-project-template/blob/main/.vscode/tasks.json) So vs code know where the header files are located.
- ! important=> We Need MinGW to run the graphics.h file

**Comment by Suryajung8** [comment]
Thankyou Now It's fixed

**Comment by SpiffGreen** [comment]
Thanks a lot. It worked for me.
