### ISSUE TITLE
testFile.exe doesnot do anything

### ISSUE THREAD

**Issue by chnlmshr** [ullaskunder3/Solutions#4]
Followed all the steps
Code was also compiled successfully
But it wouldn't run
![image](https://user-images.githubusercontent.com/60295122/129881898-29423aec-2bb1-4ee4-b69f-1cfa2f9fe7b7.png)

And I am using mingw not mingw64 or anything

**Comment by ullaskunder3** [comment]
If you are using cmd all you have to do is ` fileName.exe` just the file name and enter
If you are using bash use `./fileName.exe`

![image](https://user-images.githubusercontent.com/66258652/129890110-ed172700-192d-4e64-b683-4f427963747c.png)

Let me know...

**Comment by chnlmshr** [comment]
> If you are using cmd all you have to do is ` fileName.exe` just the file name and enter

Its not working either

**Comment by ullaskunder3** [comment]
> > If you are using cmd all you have to do is ` fileName.exe` just the file name and enter
> 
> Its not working either

Can you share the code so I can reproduce the same and also the command you're using to execute...
