### ISSUE TITLE
Thanks for the solution but I seem to be having trouble when I run the build task

### ISSUE THREAD

**Issue by arshkhans** [ullaskunder3/Solutions#5]
I keep getting the skipping incompatible error.
[SS Link](https://imgur.com/QfV1DEb)

**Comment by ullaskunder3** [comment]
![image](https://user-images.githubusercontent.com/66258652/131340757-f67f5b99-1cfe-4185-8d19-8965a2d16a9e.png)
please use MinGW not mingW64 : )
