### ISSUE TITLE
[Question] What's the difference between graphics.h and winbgim.h

### ISSUE THREAD

**Issue by o0Mardev** [ullaskunder3/Solutions#7]
I was wondering what's the difference between graphics.h and winbgim.h i compared them and they are the same.
In the official site https://winbgim.codecutter.org/ they are both inluded.

Btw I'm doing a similar guide but in Italian, shoudl I mention you?

**Comment by ullaskunder3** [comment]
Yes, why not.... 😀

And yes Both `winbgim.h` and `graphics.h` content's are same. I think `winbgim.h` is the older version of the Turbo `WinBGIm` library...

**Comment by o0Mardev** [comment]
Okay, thanks for the reply! 👍
